src/data/navigation/sections/events.js, src/pages/events/commands.md
This pull request (PR) adds docs for the following commands
events:create-event-provider
events:subscribe
events:unsubscribe
events:list
-  ...
-  ...
=> Add event commands

src/pages/events/commands.md
This pull request (PR) removes instances of the term "eventing".
-  ...
-  ...
=> Remove instances of eventing

src/pages/events/configure-commerce.md
This pull request (PR) add cron info to the Commerce configuration topic.
-  ...
-  ...
=> Add cron info

src/pages/events/configure-commerce.md
This pull request (PR) updates the Commerce configuration topic to include new Cloud information.
-  ...
-  ...
=> Update Cloud configuration procedure

gatsby-config.js
This pull request (PR) updates the `.gatsby-config.js` file to account for the new repo name
-  ...
-  ...
=> Update .gatsby-config.js file

src/pages/events/commands.md, src/pages/events/configure-commerce.md
Updates the example command in the Commerce configutation topic. This should have been part of #55
=> Update configutation step

src/pages/events/commands.md, src/pages/events/configure-commerce.md, src/pages/events/project-setup.md
This PR updates the docs based on partner feedback.
=> Partner feedback

src/pages/events/configure-commerce.md
Updates the Cloud installation instructions to account for the release of ECE tools 2002.1.13
=> Update Cloud install instructions

src/pages/events/configure-commerce.md
This PR updates the description of the Adobe Commerce Instance ID field.
=> Add restrictions to instance ID

src/pages/events/module-development.md
This fixes a page where two code samples are displayed as one due to missing closing code tag
=> Fix for broken XML example

src/pages/events/configure-commerce.md
Adds ability to change environment type
=> Adding ability to change environment type

src/pages/index.md
This PR updates front page of the commerce-events repo, removing the traces of the previous name of the repo, which was commerce-extensibility.
=> Update front page

src/pages/get-started/configure-commerce.md
This PR adds the Event retention time field.
=> Add Event retention time field

src/data/navigation/header.js
This pull request updates the top navigation
=> Update top nav

src/data/navigation/sections/get-started.js, src/pages/get-started/release-notes.md
This PR adds the release notes topic.
=> Create release notes

src/pages/get-started/module-development.md
This PR adds example  resource model events.
=> Add resource model examples

src/pages/get-started/installation.md, src/pages/get-started/module-development.md, src/pages/get-started/release-notes.md
This PR provides updates for version 1.0.1
whatsnew
Added release notes and update instructions for V1.0.1.
=> Add V1.0.1 info

package.json, yarn.lock
Upgrade the aio theme and gatsby to latest  supported versions.
Use latest fixes and features available.
Ran `yarn start` locally.
=> Upgrade theme and gatsby

src/pages/get-started/module-development.md
This PR clarifies the capabilities of the `events:list:all` command.
=> Clarification about list:all

.github/workflows/add-to-project-board.yml
This PR adds a GitHub workflow to add Pull Requests and Issues to the Commerce project boards.
=> Add GH Action workflow for issues and PRs

src/pages/get-started/module-development.md
This pull request (PR) updates #114 
I intended to completely overhaul the "Commerce module development" topic after I merged 114, but I don't have  time to do so right now. This update contains the edits I should have made before merging 114.
- ...
- ...
=> Updates to PR-114

src/pages/get-started/release-notes.md
This pull request (PR) updates the release notes for version 1.1.0.
- ...
- ...
whatsnew
Updated the [release notes](https://developer.adobe.com/commerce/events/get-started/release-notes/) for V1.1.0.
=> V1.1.0 release notes

src/pages/get-started/release-notes.md
This pull request (PR) adds release note for v1.2.0
- ...
- ...
=> 1.2.0 release notes

src/data/navigation/sections/get-started.js, src/pages/get-started/custom-event-fields.md, src/pages/get-started/module-development.md
This pull request (PR) fleshes out the work that originally added in #156. It creates a new topic and adds guidance for creating processor classes.
- ...
- ...
=> Add custom fields to events

src/pages/get-started/release-notes.md
This pull request (PR) adds release notes for the Aug 24 release.
- ...
- ...
=> Add release notes
